document.addEventListener('DOMContentLoaded', () => {

    // --- Hero Carousel ---
    const carouselItems = document.querySelectorAll('.carousel-item');
    const prevBtn = document.querySelector('.carousel-prev');
    const nextBtn = document.querySelector('.carousel-next');

    let currentSlide = 0;
    const totalSlides = carouselItems.length;

    function showSlide(index) {
        carouselItems.forEach(item => item.classList.remove('active'));
        currentSlide = (index + totalSlides) % totalSlides;
        carouselItems[currentSlide].classList.add('active');
    }

    if (prevBtn && nextBtn && totalSlides > 0) {
        nextBtn.addEventListener('click', () => showSlide(currentSlide + 1));
        prevBtn.addEventListener('click', () => showSlide(currentSlide - 1));
        setInterval(() => showSlide(currentSlide + 1), 5000);
    }


    // --- Project Data (folder-driven) ---
    // Each project lives in projects/<slug>/ with:
    //   project.json          (metadata)
    //   cover.{jpg,png,webp}  (gallery thumbnail)
    //   images/manifest.json  (ordered list of overlay images — URLs or "images/<file>")
    // The top-level projects/manifest.json (auto-generated by tools/build-manifest.js)
    // lists the slugs in display order.

    const PROJECTS_BASE = 'projects';

    // Two sources of project data:
    //   1. /api/projects — used when the server is running, gives us live `stock`.
    //   2. projects/manifest.json + per-slug project.json — used as a fallback.
    // We prefer the API so the cart reflects real-time inventory.
    let projects = [];

    async function fetchJSON(url) {
        const res = await fetch(url, { cache: 'no-cache' });
        if (!res.ok) throw new Error(`Failed to load ${url} (${res.status})`);
        return res.json();
    }

    function resolveImageRef(slug, ref) {
        if (/^https?:\/\//i.test(ref)) return ref;
        return `${PROJECTS_BASE}/${slug}/${ref}`;
    }

    async function loadProjectStatic(slug) {
        const meta = await fetchJSON(`${PROJECTS_BASE}/${slug}/project.json`);
        const coverExts = ['jpg', 'png', 'webp'];
        let cover = null;
        for (const ext of coverExts) {
            const candidate = `${PROJECTS_BASE}/${slug}/cover.${ext}`;
            try {
                const res = await fetch(candidate, { method: 'HEAD', cache: 'no-cache' });
                if (res.ok) { cover = candidate; break; }
            } catch (_) { /* ignore */ }
        }
        let images = [];
        try {
            const list = await fetchJSON(`${PROJECTS_BASE}/${slug}/images/manifest.json`);
            images = list.map(ref => resolveImageRef(slug, ref));
        } catch (_) { /* no manifest */ }
        return { slug, ...meta, cover, images };
    }

    async function loadProjectsStatic() {
        const slugs = await fetchJSON(`${PROJECTS_BASE}/manifest.json`);
        return Promise.all(slugs.map(loadProjectStatic));
    }

    async function loadProjects() {
        try {
            const data = await fetchJSON('/api/projects');
            // The API returns projects with `cover` and `images` already resolved and `stock` live.
            return data.projects || [];
        } catch (e) {
            // Server is not running — fall back to static.
            console.warn('Falling back to static project loading:', e.message);
            return loadProjectsStatic();
        }
    }

    function renderGallery(list) {
        const grid = document.querySelector('.gallery-grid');
        if (!grid) return;
        grid.innerHTML = '';
        list.forEach(p => {
            const item = document.createElement('div');
            item.className = 'gallery-item';
            if ((p.stock || 0) <= 0 || p.status === 'sold') {
                item.classList.add('sold-out');
            }

            const img = document.createElement('img');
            img.src = p.cover || '';
            img.alt = p.title || '';
            item.appendChild(img);

            const overlay = document.createElement('div');
            overlay.className = 'overlay';
            overlay.innerHTML = '<span>View Project</span>';
            item.appendChild(overlay);

            item.addEventListener('click', () => openProjectOverlay(p));
            grid.appendChild(item);
        });
    }

    // Keep the cart drawer in sync whenever the cart changes.
    document.addEventListener('cart:rerender', () => {
        if (window.cart && projects.length) {
            window.cart.render(projects);
        }
    });

    async function initGallery() {
        const grid = document.querySelector('.gallery-grid');
        try {
            projects = await loadProjects();
            renderGallery(projects);
            // Initial drawer render (in case it's opened before any change).
            if (window.cart) window.cart.render(projects);
        } catch (err) {
            console.error('Could not load projects:', err);
            if (grid) {
                grid.innerHTML = '<p style="grid-column:1/-1;text-align:center;color:#888;padding:2rem;">No projects available.</p>';
            }
        }
    }


    // --- Project Overlay ---
    const overlay        = document.getElementById('project-overlay');
    const overlayMainImg = document.getElementById('overlay-main-img');
    const overlayThumbs  = document.getElementById('overlay-thumbnails');
    const elCategory     = document.getElementById('overlay-category');
    const elTitle        = document.getElementById('overlay-title');
    const elDescription  = document.getElementById('overlay-description');
    const elYear         = document.getElementById('overlay-year');
    const elMedium       = document.getElementById('overlay-medium');
    const elDimensions   = document.getElementById('overlay-dimensions');
    const elEdition      = document.getElementById('overlay-edition');
    const elPrice        = document.getElementById('overlay-price');
    const elStatusBadge  = document.getElementById('overlay-status-badge');
    const btnAddToCart   = document.getElementById('btn-add-to-cart');
    const btnEnquire     = document.getElementById('btn-enquire');
    const overlayClose   = document.querySelector('.overlay-close');
    const imgPrev        = document.querySelector('.overlay-img-prev');
    const imgNext        = document.querySelector('.overlay-img-next');
    const cartToast      = document.getElementById('cart-toast');

    // Quantity stepper inside the overlay.
    const overlayQtyBox     = document.getElementById('overlay-qty');
    const overlayQtyValue   = document.getElementById('overlay-qty-value');
    const overlayQtyDec     = document.getElementById('overlay-qty-dec');
    const overlayQtyInc     = document.getElementById('overlay-qty-inc');
    const overlayStockEl    = document.getElementById('overlay-stock');

    let currentProject    = null;
    let currentImageIndex = 0;
    let currentQty        = 1;

    function setImage(index) {
        if (!currentProject || !currentProject.images.length) return;
        currentImageIndex = (index + currentProject.images.length) % currentProject.images.length;
        overlayMainImg.style.opacity = 0;
        setTimeout(() => {
            overlayMainImg.src = currentProject.images[currentImageIndex];
            overlayMainImg.style.opacity = 1;
        }, 150);
        overlayThumbs.querySelectorAll('img').forEach((thumb, i) => {
            thumb.classList.toggle('active', i === currentImageIndex);
        });
    }

    function isBuyable(project) {
        if (!project) return false;
        if (project.status === 'sold' || project.status === 'enquire') return false;
        return Number.isInteger(project.stock) ? project.stock > 0 : true;
    }

    function updateQtyUI() {
        if (!currentProject) return;
        const max = Number.isInteger(currentProject.stock) ? currentProject.stock : 99;
        currentQty = Math.max(1, Math.min(max, currentQty));
        overlayQtyValue.textContent = currentQty;
        if (overlayQtyDec) overlayQtyDec.disabled = currentQty <= 1;
        if (overlayQtyInc) overlayQtyInc.disabled = currentQty >= max;
    }

    function openProjectOverlay(project) {
        currentProject    = project;
        currentImageIndex = 0;
        currentQty        = 1;

        elCategory.textContent    = project.category || '';
        elTitle.textContent       = project.title || '';
        elDescription.textContent = project.description || '';
        elYear.textContent        = project.year || '';
        elMedium.textContent      = project.medium || '';
        elDimensions.textContent  = project.dimensions || '';
        elEdition.textContent     = project.edition || '';
        elPrice.textContent       = project.price || '';

        const statusLabels = { available: 'Available', sold: 'Sold', enquire: 'Price on Request' };
        elStatusBadge.textContent  = statusLabels[project.status] || project.status || '';
        elStatusBadge.className    = 'overlay-status-badge ' + (project.status || '');

        const buyable = isBuyable(project);
        const stock = Number.isInteger(project.stock) ? project.stock : null;

        // Stock label below the price row.
        if (overlayStockEl) {
            if (stock === null) {
                overlayStockEl.textContent = '';
                overlayStockEl.hidden = true;
            } else if (stock === 0) {
                overlayStockEl.textContent = 'Sold out';
                overlayStockEl.className = 'overlay-stock out';
                overlayStockEl.hidden = false;
            } else if (stock <= 3) {
                overlayStockEl.textContent = `Only ${stock} left`;
                overlayStockEl.className = 'overlay-stock low';
                overlayStockEl.hidden = false;
            } else {
                overlayStockEl.textContent = `${stock} in stock`;
                overlayStockEl.className = 'overlay-stock';
                overlayStockEl.hidden = false;
            }
        }

        // Quantity stepper.
        if (overlayQtyBox) overlayQtyBox.hidden = !buyable;

        // Add to Cart / Enquire buttons.
        if (btnEnquire) btnEnquire.hidden = project.status === 'enquire' ? false : true;

        btnAddToCart.disabled    = !buyable;
        btnAddToCart.textContent = !buyable
            ? (project.status === 'sold' ? 'Sold Out'
               : project.status === 'enquire' ? 'Contact for Price' : 'Unavailable')
            : 'Add to Cart';

        updateQtyUI();

        overlayThumbs.innerHTML = '';
        (project.images || []).forEach((src, i) => {
            const thumb = document.createElement('img');
            thumb.src = src;
            thumb.alt = '';
            if (i === 0) thumb.classList.add('active');
            thumb.addEventListener('click', () => setImage(i));
            overlayThumbs.appendChild(thumb);
        });

        if (project.images && project.images.length) {
            overlayMainImg.style.opacity = 1;
            overlayMainImg.src = project.images[0];
        } else {
            overlayMainImg.src = project.cover || '';
        }

        overlay.classList.add('active');
        document.body.style.overflow = 'hidden';
    }

    function closeProjectOverlay() {
        overlay.classList.remove('active');
        document.body.style.overflow = '';
    }

    overlayClose.addEventListener('click', closeProjectOverlay);

    overlay.addEventListener('click', e => {
        if (e.target === overlay) closeProjectOverlay();
    });

    document.addEventListener('keydown', e => {
        if (!overlay.classList.contains('active')) return;
        if (e.key === 'Escape')      closeProjectOverlay();
        if (e.key === 'ArrowLeft')   setImage(currentImageIndex - 1);
        if (e.key === 'ArrowRight')  setImage(currentImageIndex + 1);
    });

    imgPrev.addEventListener('click', () => setImage(currentImageIndex - 1));
    imgNext.addEventListener('click', () => setImage(currentImageIndex + 1));

    if (overlayQtyDec) overlayQtyDec.addEventListener('click', () => { currentQty -= 1; updateQtyUI(); });
    if (overlayQtyInc) overlayQtyInc.addEventListener('click', () => { currentQty += 1; updateQtyUI(); });


    // --- Cart actions ---
    let toastTimer = null;

    function showToast(message) {
        cartToast.textContent = message;
        cartToast.classList.add('show');
        clearTimeout(toastTimer);
        toastTimer = setTimeout(() => cartToast.classList.remove('show'), 2800);
    }

    btnAddToCart.addEventListener('click', () => {
        if (!currentProject) return;
        if (!isBuyable(currentProject)) return;
        if (window.cart) {
            window.cart.add(currentProject.slug, currentQty);
            showToast(`Added to cart — ${currentProject.title} × ${currentQty}`);
            // Open the drawer so the user can see what was added.
            window.cart.open();
        }
    });

    btnEnquire.addEventListener('click', () => {
        window.location.href = 'contact.html';
    });

    // Success / cancel query-string handling.
    try {
        const params = new URLSearchParams(window.location.search);
        if (params.get('checkout') === 'success') {
            showToast('Payment received. Thank you!');
            if (window.cart) window.cart.clear();
            window.history.replaceState({}, '', window.location.pathname);
        } else if (params.get('checkout') === 'cancel') {
            showToast('Checkout cancelled.');
            window.history.replaceState({}, '', window.location.pathname);
        }
    } catch (_) { /* ignore */ }


    // --- Theme toggle (light / dark) ---
    // The inline <head> script on each page has already applied the saved theme
    // before paint to avoid FOUC. Here we just render the right icon and wire the
    // click handler.
    const THEME_KEY = 'portfolio:theme';
    const themeToggleBtn = document.getElementById('theme-toggle');
    const themeToggleIcon = document.getElementById('theme-toggle-icon');

    function getSavedTheme() {
        try {
            const t = localStorage.getItem(THEME_KEY);
            return t === 'dark' ? 'dark' : 'light';
        } catch (_) {
            return 'light';
        }
    }

    function currentTheme() {
        return document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
    }

    // Sun = light mode, moon = dark mode.
    const ICONS = { light: '\u2600', dark: '\u263E' };

    function renderThemeIcon(theme) {
        if (!themeToggleIcon) return;
        themeToggleIcon.textContent = ICONS[theme] || ICONS.light;
        if (themeToggleBtn) {
            themeToggleBtn.setAttribute('aria-label',
                theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode');
        }
    }

    function setTheme(theme) {
        if (theme === 'dark') {
            document.documentElement.setAttribute('data-theme', 'dark');
        } else {
            document.documentElement.removeAttribute('data-theme');
        }
        try { localStorage.setItem(THEME_KEY, theme); } catch (_) { /* ignore */ }
        renderThemeIcon(theme);
    }

    if (themeToggleBtn) {
        // Initial icon to match whatever the <head> script applied.
        renderThemeIcon(currentTheme());

        themeToggleBtn.addEventListener('click', () => {
            setTheme(currentTheme() === 'dark' ? 'light' : 'dark');
        });
    }

    // Expose for debugging / future code.
    window.theme = {
        get: currentTheme,
        set: setTheme,
    };


    // --- Boot ---
    initGallery();
});
